name: Super-Linter

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Super-Linter
        uses: github/super-linter@v4
        env:
          RUN_LOCAL: false
          DEFAULT_BRANCH: main
